//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMAP.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMAP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   아니오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_No_data {
            get {
                return ResourceManager.GetString("Dialog_No_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 내용으로 저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_Save_Message {
            get {
                return ResourceManager.GetString("Dialog_Save_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_Save_Success {
            get {
                return ResourceManager.GetString("Dialog_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_Save_Title {
            get {
                return ResourceManager.GetString("Dialog_Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///   {&quot;KeyIndex&quot;:0,&quot;KeyPatten&quot;:0,&quot;IsEncrypted&quot;:false,&quot;KeyData&quot;:&quot;{\&quot;ApiUrl\&quot;:\&quot;https://52.79.166.67\&quot;, \&quot;ApiUserId\&quot;:\&quot;bzapi_system\&quot;, \&quot;ApiPassword\&quot;:\&quot;a#12!08@\&quot;, \&quot;Secret\&quot;:\&quot;\&quot;}&quot;}
        ///]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버키가 설정되어 있지 않습니다. 서버를 선택 하여 주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_EMPTY_SERVER_KEY {
            get {
                return ResourceManager.GetString("STR_EMPTY_SERVER_KEY", resourceCulture);
            }
        }
    }
}
